Option to open console in default browser (#5)
* Add option for opening AWS console in default browser. Only MacOS for now.

* Document -b in help and README

* A little extract function refactoring

* Simplify exit code

* Go explicitly to console for selected region when opening browser

diff --git a/assume-aws-sso-role b/assume-aws-sso-role
--- a/assume-aws-sso-role
+++ b/assume-aws-sso-role
@@ -7,9 +7,17 @@ credentials_path="${XDG_CACHE_HOME:-"$HOME/.cache"}/aws_az_credentials/"
 quiet=false
 action=output_json
 (return 0 2>/dev/null) && sourced=1 || sourced=0
+if [ ${sourced} -eq 0 ]; then
+  exit_cmd=exit
+else
+  exit_cmd=return
+fi
 
 az_access_token_api="api://3cd4d944-d89b-401b-b2ae-fb1ece182362"
 tenant=1d063515-6cad-4195-9486-ea65df456faa
+aws_federation_signin_url="https://us-east-1.signin.aws.amazon.com/federation"
+federation_destination_url="https://REGION.console.aws.amazon.com"
+logout_url="https://us-east-1.signin.aws.amazon.com/oauth?Action=logout"
 
 aws_profile=
 aws_provider=
@@ -51,17 +59,31 @@ local_time_for() {
   fi
 }
 
-output_from_credentials() {
-  if [ ${action} = set_env_vars ]; then
-    echo_maybe "Setting environment variables"
-    export AWS_ACCESS_KEY_ID=$(echo $1 | jq -r '.AccessKeyId')
-    export AWS_SECRET_ACCESS_KEY=$(echo $1 | jq -r '.SecretAccessKey')
-    export AWS_SESSION_TOKEN=$(echo $1 | jq -r '.SessionToken')
-    export AWS_DEFAULT_REGION=${DEFAULT_REGION}
-    export AWS_REGION=${aws_region}
-  else
-    echo $1
-  fi
+perform_action_for_credentials() {
+  case ${action} in
+    open_in_browser)
+      open_in_browser "$1"
+      if [ $? != 0 ]; then
+        echo >&2 "Open in browser failed."
+        return 1
+      fi
+      ;;
+    set_env_vars)
+      echo_maybe "Setting environment variables"
+      export AWS_ACCESS_KEY_ID=$(echo $1 | jq -r '.AccessKeyId')
+      export AWS_SECRET_ACCESS_KEY=$(echo $1 | jq -r '.SecretAccessKey')
+      export AWS_SESSION_TOKEN=$(echo $1 | jq -r '.SessionToken')
+      export AWS_DEFAULT_REGION=${DEFAULT_REGION}
+      export AWS_REGION=${aws_region}
+      ;;
+    output_json)
+      echo $1
+      ;;
+    *)
+      echo >&2 Unknown action ${action}
+      return 1
+      ;;
+  esac
 }
 
 account_number_from_role_arn() {
@@ -97,13 +119,43 @@ role_info_from_profile() {
   set_account_and_role_from_role_arn
 }
 
+url_encode() {
+  echo "$1" | jq "@uri" -jR
+}
+
+signin_token_for() {
+  local get_signin_token_params=$(echo $1 | jq '. + {"sessionId": .AccessKeyId, "sessionKey": .SecretAccessKey, "sessionToken": .SessionToken} | del(.AccessKeyId) | del(.SecretAccessKey) | del(.SessionToken) | del(.Version) | del(.Expiration)')
+  curl --silent --get --data-urlencode "Action=getSigninToken" --data-urlencode "Session=${get_signin_token_params}" ${aws_federation_signin_url} | jq -r .SigninToken
+}
+
+browser_url() {
+  local signin_token=$(signin_token_for "$1")
+  local federation_destination_url_encoded=$(url_encode ${federation_destination_url//REGION/${aws_region}})
+  local federation_url="${aws_federation_signin_url}?Action=login&Issuer=&SigninToken=${signin_token}&Destination=${federation_destination_url_encoded}"
+  local federation_url_encoded=$(url_encode ${federation_url})
+  echo "${logout_url}&redirect_uri=${federation_url_encoded}"
+}
+
+open_in_browser() {
+    if [ ${platform} = Darwin ]; then
+      open $(browser_url "$1")
+    else
+      echo >&2 "Unsupported platform"
+      return 1
+    fi
+}
+
 load_credentials_from_file() {
   credentials=$(cat ${credentials_file})
   expiration=$(echo ${credentials} | jq -r ".Expiration")
   expiration_in_seconds=$(date_to_seconds ${expiration})
   now_in_seconds=$(date "+%s")
   if [ ${expiration_in_seconds} -gt ${now_in_seconds} ]; then
-    output_from_credentials "${credentials}"
+    perform_action_for_credentials "${credentials}"
+    if [ $? != 0 ]; then
+      echo >&2 "Performing action ${action} failed."
+      return 1
+    fi
     echo_maybe "Credentials expires at $(local_time_for ${expiration})"
     return 0
   else
@@ -117,6 +169,10 @@ exclusive ways: Either an account number and role is supplied on the command
 line or a profile name referring to a profile in AWS's config file is supplied.
 
 Common options:
+
+    -h: Print this help and exit.
+
+    -b: Open AWS console in default browser
 
     -d: The AWS session duration in seconds. Defaults to 3600 seconds (1 hour).
 
@@ -167,18 +223,17 @@ function help() {
 }
 
 OPTIND=1
-while getopts "hjqva:d:r:p:e:" option; do
+while getopts "hbjqva:d:r:p:e:" option; do
   case "${option}" in
     h)
       help
-      if [ ${sourced} = 0 ]; then
-        exit 0
-      else
-        return 0
-      fi
+      ${exit_cmd} 0
       ;;
     a)
       aws_account=$OPTARG
+      ;;
+    b)
+      action=open_in_browser
       ;;
     e)
       aws_region=$OPTARG
@@ -203,11 +258,7 @@ while getopts "hjqva:d:r:p:e:" option; do
       ;;
     *)
       echo >&2 Unknown option ${option}
-      if [ ${sourced} = 0 ]; then
-        exit 1
-      else
-        return 1
-      fi
+      ${exit_cmd} 1
       ;;
   esac
 done
@@ -215,31 +266,19 @@ shift "$((OPTIND - 1))"
 
 if [ ! -z "${aws_profile}" ] && [[ ! -z "${aws_account}" || ! -z "${aws_role}" ]]; then
   echo >&2 Profile and account/role options are not allowed at the same time
-  if [ ${sourced} = 0 ]; then
-    exit 2
-  else
-    return 2
-  fi
+  ${exit_cmd} 2
 fi
 
 if [[ -z "${aws_profile}" && -z "${aws_account}" && -z "${aws_role}" ]]; then
   echo >&2 Either -p or -a and -r must be provided
-  if [ ${sourced} = 0 ]; then
-    exit 4
-  else
-    return 4
-  fi
+  ${exit_cmd} 4
 fi
 
 if [ ! -z "${aws_profile}" ]; then
   role_info_from_profile
   if [ $? -ne 0 ]; then
-    echo >&2 Role ARN for profile ${aws_profile} not found.
-    if [ ${sourced} = 0 ]; then
-      exit 3
-    else
-      return 3
-    fi
+    echo >&2 "Role ARN for profile ${aws_profile} not found."
+    ${exit_cmd} 3
   fi
 else
   set_role_arn_from_account_and_role
@@ -250,11 +289,7 @@ if [ -f "${credentials_file}" ]; then
   echo_maybe "Loading credentials from file"
   load_credentials_from_file
   if [ $? = 0 ]; then
-    if [ ${sourced} = 0 ]; then
-      exit 0
-    else
-      return 0
-    fi
+    ${exit_cmd} 0
   fi
 fi
 
@@ -277,21 +312,13 @@ if [ $? != 0 ]; then
   az login --output none --tenant ${tenant} 2>/dev/null
   if [ $? != 0 ]; then
     echo >&2 Login failed
-    if [ ${sourced} = 0 ]; then
-      exit 3
-    else
-      return 3
-    fi
+    ${exit_cmd} 3
   fi
   echo_maybe "Retry getting access token"
   access_token=$(az account get-access-token --resource ${az_access_token_api} --query accessToken --output tsv)
   if [ $? != 0 ]; then
     echo >&2 Acquire access token failed
-    if [ ${sourced} = 0 ]; then
-      exit 3
-    else
-      return 3
-    fi
+    ${exit_cmd} 3
   fi
 fi
 echo_maybe "Access token is $access_token"
@@ -305,20 +332,16 @@ echo_maybe "SAML token is $saml_token"
 echo_maybe "Assuming role in AWS using role ARN ${aws_role_arn} and principal ${aws_provider}"
 aws_token=$(env -u AWS_PROFILE aws sts assume-role-with-saml --duration-seconds ${aws_session_duration} --region ${aws_region} --role-arn "$aws_role_arn" --principal-arn "$aws_provider" --saml-assertion "$saml_token" --query "Credentials" | jq ".Version = 1")
 if [ $? != 0 ]; then
-  echo >&2 Acquire AWS token failed
-  if [ ${sourced} = 0 ]; then
-    exit 3
-  else
-    return 3
-  fi
+  echo >&2 "Acquire AWS token failed"
+  ${exit_cmd} 3
 fi
 echo_maybe "aws_token is ${aws_token}"
 
 expiration=$(echo ${aws_token} | jq -r ".Expiration")
 echo_maybe "Token expires at ${expiration}"
 
-echo ${aws_token} >${credentials_file}
-output_from_credentials "${aws_token}"
+echo "${aws_token}" >${credentials_file}
 
+perform_action_for_credentials "${aws_token}"
 expiration=$(echo ${aws_token} | jq -r ".Expiration")
 echo_maybe "Credentials expires at $(local_time_for ${expiration})"
